# Generated by Django 6.0.4 on 2026-04-29 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbonoFiado',
            fields=[
                ('id_abono', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pago', models.DateTimeField()),
                ('monto', models.IntegerField()),
            ],
            options={
                'db_table': 'abono_fiado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AjusteInventario',
            fields=[
                ('id_ajuste', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_ajuste', models.DateTimeField()),
                ('cantidad', models.IntegerField()),
                ('motivo', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'ajuste_inventario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CajaSesion',
            fields=[
                ('id_sesion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('monto_apertura', models.IntegerField()),
                ('monto_cierre_real', models.IntegerField(blank=True, null=True)),
                ('monto_cierre_esperado', models.IntegerField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'caja_sesion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClienteFiado',
            fields=[
                ('rut', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'cliente_fiado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_comuna', models.CharField(max_length=60)),
                ('region', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'comuna',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id_detalle_factura', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('valor_compra', models.IntegerField()),
            ],
            options={
                'db_table': 'detalle_factura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.IntegerField()),
            ],
            options={
                'db_table': 'detalle_venta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DuenoTienda',
            fields=[
                ('id_dueno', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('primer_apellido', models.CharField(max_length=25)),
                ('segundo_apellido', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'dueno_tienda',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id_factura', models.AutoField(primary_key=True, serialize=False)),
                ('folio_factura', models.IntegerField()),
                ('es_compra_directa', models.BooleanField()),
                ('fecha_emision', models.DateField()),
                ('fecha_ingreso', models.DateField()),
            ],
            options={
                'db_table': 'factura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stock_actual', models.IntegerField()),
                ('precio_venta', models.IntegerField()),
                ('umbral_seguridad', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'inventario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('cod_barra', models.DecimalField(decimal_places=0, max_digits=20, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=120)),
                ('volumen', models.IntegerField()),
                ('marca', models.CharField(max_length=80)),
                ('fabricante', models.CharField(max_length=80)),
                ('categoria', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('rut_tienda', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('tipo_tienda', models.CharField(max_length=30)),
                ('calle', models.CharField(max_length=60)),
                ('numero', models.IntegerField()),
                ('detalle', models.CharField(blank=True, max_length=60, null=True)),
                ('id_comuna', models.IntegerField()),
                ('id_dueno', models.IntegerField()),
            ],
            options={
                'db_table': 'tienda',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=40, unique=True)),
                ('nombre', models.CharField(max_length=25)),
                ('primer_apellido', models.CharField(max_length=25)),
                ('segundo_apellido', models.CharField(max_length=25)),
                ('rol', models.CharField(max_length=50)),
                ('mail', models.CharField(max_length=100)),
                ('ultimo_ingreso', models.DateTimeField(blank=True, null=True)),
                ('password', models.CharField(max_length=25)),
                ('requiere_cambio_pass', models.BooleanField(default=False)),
                ('es_activo', models.BooleanField()),
                ('fecha_creacion', models.DateTimeField()),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_venta', models.DateTimeField()),
                ('total_neto', models.IntegerField()),
                ('iva', models.IntegerField()),
                ('total_bruto', models.IntegerField()),
                ('estado_pago', models.BooleanField()),
            ],
            options={
                'db_table': 'venta',
                'managed': False,
            },
        ),
    ]
