from django.urls import path
from .views import (buscar_producto_por_codigo, registrar_venta, pantalla_pos, consultar_deuda_cliente, registrar_abono,
                    pantalla_recaudacion, abrir_caja, obtener_estado_cuadratura, pantalla_apertura_caja, registrar_cierre,
                    pantalla_cierre_caja, pantalla_login, cerrar_sesion, pantalla_dashboard, pantalla_catalogo,
                    registrar_producto, pantalla_abastecimiento, registrar_abastecimiento_api, api_buscar_productos,
                    pantalla_ajustes, registrar_ajuste_api, pantalla_configuracion, registrar_usuario,api_reset_clave,
                    api_cambiar_estado, pantalla_recuperar_password, procesar_recuperacion, pantalla_reportes, pantalla_consola_analista,
                    exportar_inventario_excel, api_buscar_cliente, procesar_cambio_password, pantalla_corporativa,
                    gestion_tiendas_corporativo, gestion_usuarios_corporativo)

urlpatterns = [
    #rutas API backend/JSON
    path('api/producto/buscar/', buscar_producto_por_codigo, name='buscar_producto'),
    path('api/venta/registrar/', registrar_venta, name='registrar_venta'),
    path('api/fiado/estado/', consultar_deuda_cliente, name='estado_fiado'),
    path('api/fiado/pagar/', registrar_abono, name='pagar_fiado'),
    path('api/caja/abrir/', abrir_caja, name='abrir_caja'),
    path('api/caja/estado/', obtener_estado_cuadratura, name='estado_caja'),
    path('api/caja/cerrar/', registrar_cierre, name='cerrar_caja'),
    path('api/abastecimiento/registrar/', registrar_abastecimiento_api, name='registrar_abastecimiento_api'),
    path('api/productos/buscar/', api_buscar_productos, name='api_buscar_productos'),
    path('api/inventario/ajustar/', registrar_ajuste_api, name='registrar_ajuste_api'),
    path('api/usuarios/reset-clave/', api_reset_clave, name='api_reset_clave'),
    path('api/usuarios/cambiar-estado/', api_cambiar_estado, name='api_cambiar_estado'),
    path('api/cliente/buscar/', api_buscar_cliente, name='api_buscar_cliente'),
    
    #ruta frontend
    path('pos/', pantalla_pos, name='pantalla_pos'),
    path('recaudacion/', pantalla_recaudacion, name='pantalla_recaudacion'),
    path('caja/apertura/', pantalla_apertura_caja, name='pantalla_apertura_caja'),
    path('caja/cierre/', pantalla_cierre_caja, name='pantalla_cierre_caja'),
    path('login/', pantalla_login, name='pantalla_login'),
    path('logout/', cerrar_sesion, name='cerrar_sesion'),
    path('dashboard/', pantalla_dashboard, name='pantalla_dashboard'),
    path('dashboard/productos/', pantalla_catalogo, name='pantalla_catalogo'),
    path('dashboard/productos/registrar/', registrar_producto, name='registrar_producto'),
    path('dashboard/abastecimiento/', pantalla_abastecimiento, name='pantalla_abastecimiento'),
    path('dashboard/ajustes/', pantalla_ajustes, name='pantalla_ajustes'),
    path('dashboard/configuracion/', pantalla_configuracion, name='pantalla_configuracion'),
    path('dashboard/configuracion/registrar/', registrar_usuario, name='registrar_usuario'),
    path('login/recuperar/', pantalla_recuperar_password, name='pantalla_recuperar_password'),
    path('login/recuperar/procesar/', procesar_recuperacion, name='procesar_recuperacion'),
    path('dashboard/reportes/', pantalla_reportes, name='pantalla_reportes'),
    path('dashboard/analista/', pantalla_consola_analista, name='pantalla_consola_analista'),
    path('dashboard/ajustes/exportar/', exportar_inventario_excel, name='exportar_inventario_excel'),
    path('login/procesar-cambio/', procesar_cambio_password, name='procesar_cambio_password'),
    path('corporativo/', pantalla_corporativa, name='pantalla_corporativa'),
    path('corporativo/tiendas/', gestion_tiendas_corporativo, name='gestion_tiendas_corporativo'),
    path('corporativo/usuarios/', gestion_usuarios_corporativo, name='gestion_usuarios_corporativo'),
]